// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrfeyQCmxNSK2OW-GmEbMcgIYy7LF5aBQ',
    appId: '1:416402356443:android:565010bfa414a8c352b4fe',
    messagingSenderId: '416402356443',
    projectId: 'buzz-chat-a1dcf',
    storageBucket: 'buzz-chat-a1dcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPbc2mJv1yPYBNH5B9qssB5h1JQUdVIb8',
    appId: '1:416402356443:ios:c5371b0df47ccbfb52b4fe',
    messagingSenderId: '416402356443',
    projectId: 'buzz-chat-a1dcf',
    storageBucket: 'buzz-chat-a1dcf.appspot.com',
    androidClientId: '416402356443-seselg70gsbs7ifr8u1udc3ojgmfhv9q.apps.googleusercontent.com',
    iosClientId: '416402356443-jq5ugacggeocta9lnom1brs8p0a5bpqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzChat',
  );

}